---
name: 'Build docker images'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: 'terragrunt'
            dockerfile: 'terragrunt/Dockerfile'
            tags: 'antmelekhin/docker-terraform:tf-1.5.4-tg-0.48.5'
          - name: 'tflint'
            dockerfile: 'tflint/Dockerfile'
            tags: 'antmelekhin/docker-terraform:tflint-0.47.0'

    steps:
      - name: 'Checkout the codebase'
        uses: actions/checkout@v3

      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v2

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2

      - name: 'Login to DockerHub'
        uses: docker/login-action@v2
        with:
          username: 'antmelekhin'
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: 'Build and push ${{ matrix.name }}'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ matrix.tags }}
